apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-ingress
  namespace: simple-app
spec:
  ingressClassName: nginx
  rules:
  - host: stable.simple-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app-svc-{{ .Values.stable.Version }}
            port:
              number: 80
