apiVersion: v1
kind: Service
metadata:
  name: simple-app-svc-{{ .Values.stable.Version }}
  namespace: simple-app
  labels:
    app: simple-app
    service: simple-app
spec:
  selector:
    app: simple-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
